### ISSUE TITLE
Nice project, very impressive

### ISSUE THREAD

**Issue by ceddybi** [ffhan/tome#1]
- this is not really an issue, i'd like to personally thank you for creating this project

- Am planning on creating one for @stoqey but in nodejs

**Comment by ffhan** [comment]
Hi,

thank you for the kind words, best of luck with your new project!

**Comment by ceddybi** [comment]
@ffhan thank you again, wanna set up a discussion section for this

I'd like to contribute and ask questions soon

**Comment by ceddybi** [comment]
@ffhan  Settings > Discussion > Setup Discussion 

Thank you very much

**Comment by ceddybi** [comment]
@ffhan i have also started mine by the way

https://github.com/stoqey/dior

**Comment by ffhan** [comment]
@ceddybi discussions are now enabled

Cool!
